- hosts: localhost
  vars: 

  tasks:
  - name: build webapp
    docker_image: 
      path: "{{ playbook_dir }}/webapp"
      name: daily-epub/webapp
      tag: latest
      force: yes

  - name: build worker-ebook
    docker_image: 
      path: "{{ playbook_dir }}/worker-ebook"
      name: daily-epub/worker-ebook
      tag: latest
      force: yes