version: '2'
services:
  redis:
    image: redis:latest
    container_name: daily-epub-redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo:latest
    container_name: daily-epub-mongo

  ebook-worker:
    image: daily-epub-ebook-worker
    container_name: daily-epub-ebook-worker
    build:
      context: ./ebook-worker
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo

  webapp:
    image: daily-epub-webapp
    container_name: daily-epub-webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
      - ebook-worker